---
- name: Ensure Apache is installed and running on Amazon Linux
  hosts: webservers
  become: true

  tasks:
    - name: Install Apache
      ansible.builtin.yum:
        name: httpd
        state: present

    - name: Start and enable Apache
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: true

    - name: Check Apache version
      ansible.builtin.command:
        cmd: httpd -v
      register: apache_version

    - name: Print Apache version
      ansible.builtin.debug:
        var: apache_version.stdout
